name: Deploy with docker

on:
  push:
    # 分支
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: fengqixian1996/mall-app
          tags: latest
          registry: docker.io
          dockerfile: ./deploy/Dockerfile
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}
        
      - uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        name: ssh scp ssh pipelines
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          first_ssh: |-
            echo $WELCOME  &&
          #scp: |-
          last_ssh: |-
            docker stop mall-app &&  
            docker rm mall-app &&
            docker rmi fengqixian1996/mall-app:latest &&
            docker pull fengqixian1996/mall-app:latest &&
            docker run -dit --restart=always  --name mall-app -p 8081:8081 fengqixian1996/mall-app:latest &&
