name: Deploy with docker

on:
  push:
    # 分支
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: fengqixian1996/mall-app
          tags: latest
          registry: docker.io
          dockerfile: ./deploy/Dockerfile
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}
        
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1.2.2
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.DC_HOST }}
          username: ${{ secrets.DC_USER }}
          password: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          debug: true
          script: |
            echo "$WELCOME"
            docker stop mall-app || true &&
            docker rm mall-app || true &&
            docker rmi fengqixian1996/mall-app:latest || true &&
            docker pull fengqixian1996/mall-app:latest &&
            docker run -dit --restart=always --name mall-app -v /logs/mall-app/:/data/app/storage/logs -p 8080:8080 fengqixian1996/mall-app:latest
            echo "$LASTSSH"
      
